server.port=${PORT:8080}
spring.application.name=test-jpa-manager
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.change-log=liquibase/changelog.xml

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate