server.port=${PORT:8080}
spring.application.name=testjpa-sync-jdbctmpl
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

app.persistance.batch_size=100